/*
 * File: app/store/ProvinceStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.store.ProvinceStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        data: [
            {
                id: '1',
                name: '北京市'
            },
            {
                id: '2',
                name: '广东省'
            },
            {
                id: '3',
                name: '湖南省'
            }
        ],
        storeId: 'ProvinceStore',
        fields: [
            {
                name: 'id',
                type: 'string'
            },
            {
                name: 'name',
                type: 'string'
            }
        ]
    }
});