/*
 * File: app/store/WithdrawalHistoryStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.store.WithdrawalHistoryStore', {
    extend: 'Ext.data.Store',

    requires: [
        'mobile.model.WithdrawalHistory',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'mobile.model.WithdrawalHistory',
        storeId: 'WithdrawalHistoryStore',
        proxy: {
            type: 'jsonp',
            url: '/weixin/mobile/self/getWithdrawalHistoryList.htm',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        }
    }
});