/*
 * File: app/view/ForgetFrom.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.ForgetFrom', {
    extend: 'Ext.form.Panel',
    alias: 'widget.forgetform',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Label',
        'Ext.form.FieldSet',
        'Ext.field.Password'
    ],

    config: {
        height: '100%',
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '找回密码',
                items: [
                    {
                        xtype: 'button',
                        docked: 'left',
                        itemId: 'backBtn',
                        ui: 'back',
                        text: '返回'
                    }
                ]
            },
            {
                xtype: 'label',
                height: '100%',
                hidden: false,
                html: '输入手机号和微信号：',
                itemId: 'firstLabel',
                margin: 10,
                width: '90%'
            },
            {
                xtype: 'label',
                height: '100%',
                hidden: true,
                itemId: 'forgetLabel',
                margin: 10,
                width: '90%'
            },
            {
                xtype: 'label',
                height: '100%',
                hidden: true,
                html: '设置新密码：',
                itemId: 'passLabel',
                margin: 10,
                width: '90%'
            },
            {
                xtype: 'fieldset',
                itemId: 'forgetFieldSet',
                margin: 20,
                items: [
                    {
                        xtype: 'textfield',
                        centered: false,
                        itemId: 'telephone',
                        labelWidth: '80%',
                        name: 'telephone',
                        maxLength: 11,
                        placeHolder: '请输入手机号码'
                    },
                    {
                        xtype: 'textfield',
                        hidden: false,
                        itemId: 'wechatName',
                        name: 'wechatName',
                        maxLength: 30,
                        placeHolder: '请输入微信号'
                    },
                    {
                        xtype: 'textfield',
                        centered: false,
                        hidden: true,
                        itemId: 'verifycode',
                        labelWidth: '80%',
                        name: 'verifycode',
                        maxLength: 6,
                        placeHolder: '请输入验证码'
                    },
                    {
                        xtype: 'passwordfield',
                        centered: false,
                        hidden: true,
                        itemId: 'password',
                        name: 'password',
                        maxLength: 16,
                        placeHolder: '6到16个字符,区分大小写'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'getVerifyCodeBtn',
                margin: 20,
                padding: 8,
                ui: 'action',
                text: '下一步'
            },
            {
                xtype: 'button',
                hidden: true,
                itemId: 'submitBtn',
                margin: 20,
                padding: 8,
                ui: 'action',
                text: '提交'
            },
            {
                xtype: 'button',
                hidden: true,
                itemId: 'submitVerifyCodeBtn',
                margin: 20,
                padding: 8,
                ui: 'action',
                text: '下一步'
            },
            {
                xtype: 'container',
                itemId: 'bottomContainer',
                margin: '10% 25% 0% 25%',
                width: '50%',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'label',
                        height: '100%',
                        hidden: true,
                        itemId: 'tipLabel',
                        padding: 0
                    },
                    {
                        xtype: 'button',
                        height: '100%',
                        hidden: true,
                        itemId: 'tipBtn',
                        padding: 0,
                        ui: 'plain'
                    }
                ]
            }
        ]
    }

});