/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginform',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.field.Password'
    ],

    config: {
        height: '100%',
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        docked: 'right',
                        itemId: 'forgetBtn',
                        ui: 'action',
                        text: '忘记密码'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 60,
                margin: '5% 5% 1% 5%',
                scrollable: false,
                items: [
                    {
                        xtype: 'image',
                        centered: true,
                        height: 60,
                        width: 100,
                        src: 'resources/icons/Icon.png'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'loginFieldSet',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'username',
                        labelWidth: '80%',
                        name: 'j_username',
                        maxLength: 25,
                        placeHolder: '请输入您的手机号'
                    },
                    {
                        xtype: 'passwordfield',
                        itemId: 'password',
                        labelWidth: '80%',
                        name: 'j_password',
                        maxLength: 25,
                        placeHolder: '请输入您的密码'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'loginButton',
                margin: 20,
                padding: 8,
                ui: 'confirm-round',
                text: '登录'
            },
            {
                xtype: 'button',
                itemId: 'registerBtn',
                margin: 20,
                padding: 8,
                ui: 'decline-round',
                text: '注册账号'
            }
        ]
    }

});