/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.MainPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainpanel',

    requires: [
        'Ext.navigation.View',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.plugin.ListPaging',
        'Ext.plugin.PullRefresh',
        'Ext.tab.Bar'
    ],

    config: {
        id: 'mainPanel',
        layout: {
            type: 'card',
            animation: 'scroll'
        },
        items: [
            {
                xtype: 'container',
                title: '任务大厅',
                iconCls: 'list',
                itemId: 'article',
                items: [
                    {
                        xtype: 'navigationview',
                        height: '100%',
                        itemId: 'taskNavigateView',
                        defaultBackButtonText: '返回',
                        layout: {
                            type: 'card',
                            animation: 'scroll'
                        },
                        items: [
                            {
                                xtype: 'list',
                                title: '任务大厅',
                                cls: 'dataview-basic',
                                itemId: 'taskList',
                                itemTpl: [
                                    '<div class="img" style="background-image: url(\'/mobile/resources/icons/{imgUrl}\');"></div>',
                                    '<div class="content">',
                                    '    <div class="name">{title}</div>',
                                    '    <div class="affiliation">',
                                    '        <span>已完成数：{sharedCount}</span>',
                                    '        <span style="margin-left:10px">剩余可抢单数：{shareAvaliable}</span>',
                                    '        <!--<br><span>类别：{type}</span>-->',
                                    '    </div>',
                                    '</div>'
                                ],
                                loadingText: '正在加载...',
                                store: 'TaskStore',
                                plugins: [
                                    {
                                        autoPaging: true,
                                        loadMoreText: '加载更多...',
                                        noMoreRecordsText: '',
                                        type: 'listpaging'
                                    },
                                    {
                                        lastUpdatedDateFormat: 'Y-m-d H:i',
                                        lastUpdatedText: '上次刷新:',
                                        loadedText: '刷新完成',
                                        loadingText: '正在刷新...',
                                        pullText: '下拉刷新',
                                        releaseText: '释放立即刷新',
                                        scrollerAutoRefresh: true,
                                        type: 'pullrefresh'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: '我的任务',
                iconCls: 'favorites',
                itemId: 'shared',
                items: [
                    {
                        xtype: 'navigationview',
                        height: '100%',
                        itemId: 'sharedNavigateView',
                        defaultBackButtonText: '返回',
                        layout: {
                            type: 'card',
                            animation: 'scroll'
                        },
                        items: [
                            {
                                xtype: 'list',
                                title: '我的任务',
                                cls: 'dataview-basic',
                                itemId: 'sharedList',
                                itemTpl: [
                                    '<div class="img" style="background-image: url(\'/mobile/resources/icons/{imgUrl}\');"></div>',
                                    '<div class="content">',
                                    '    <div class="name">{title}</div>',
                                    '    <tpl if="status == 0">',
                                    '        <div class="affiliation">',
                                    '            状态：<span>未上传图片</span>',
                                    '        </div>',
                                    '    </tpl>',
                                    '    <tpl if="status == 1">',
                                    '        <div class="affiliation">',
                                    '            状态：<span>未提交</span>',
                                    '        </div>',
                                    '    </tpl>',
                                    '    <tpl if="status == 2">',
                                    '        <div class="affiliation">',
                                    '                <span>状态：审核中</span>',
                                    '        </div>',
                                    '        <div class="affiliation">完成时间：{sharedTime}</div>',
                                    '    </tpl>',
                                    '    <tpl if="status == 3">',
                                    '        <div class="affiliation">',
                                    '            <span>状态：审核通过</span>',
                                    '            <span style="margin-left:10px">获得奖励：{price}元</span>',
                                    '        </div>',
                                    '        <div class="affiliation">完成时间：{sharedTime}</div>',
                                    '    </tpl>',
                                    '    <tpl if="status == 4">',
                                    '        <div class="affiliation">',
                                    '            <span>状态：审核未通过</span>',
                                    '        </div>',
                                    '        <div class="affiliation">原因：{reason}</div>',
                                    '    </tpl>',
                                    '</div>'
                                ],
                                loadingText: '正在加载...',
                                store: 'SharedStore',
                                plugins: [
                                    {
                                        autoPaging: true,
                                        loadMoreText: '加载更多...',
                                        noMoreRecordsText: '',
                                        type: 'listpaging'
                                    },
                                    {
                                        lastUpdatedDateFormat: 'Y-m-d H:i',
                                        lastUpdatedText: '上次刷新:',
                                        loadedText: '刷新完成',
                                        loadingText: '正在刷新...',
                                        pullText: '下拉刷新',
                                        releaseText: '释放立即刷新',
                                        scrollerAutoRefresh: true,
                                        type: 'pullrefresh'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: '我的下线',
                iconCls: 'team',
                itemId: 'offline',
                items: [
                    {
                        xtype: 'navigationview',
                        height: '100%',
                        itemId: 'offlineNavigateView',
                        defaultBackButtonText: '返回',
                        layout: {
                            type: 'card',
                            animation: 'scroll'
                        },
                        items: [
                            {
                                xtype: 'list',
                                title: '我的下线',
                                cls: 'dataview-basic',
                                itemId: 'offlineList',
                                itemTpl: [
                                    '<div>',
                                    '    <img src="/mobile/resources/images/offline/offline.png" style="vertical-align:middle"/>',
                                    '    <span style="margin-left:5%;">{phoneNumber}</span>',
                                    '    <span style="margin-left:30%;color:blue">{sharedPay}元</span>',
                                    '</div>'
                                ],
                                loadingText: '正在加载...',
                                scrollToTopOnRefresh: false,
                                store: 'OfflineStore',
                                grouped: true
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: '我',
                iconCls: 'user',
                itemId: 'self',
                items: [
                    {
                        xtype: 'navigationview',
                        height: '100%',
                        itemId: 'selfNavigateView',
                        defaultBackButtonText: '返回',
                        layout: {
                            type: 'card',
                            animation: 'flip'
                        },
                        items: [
                            {
                                xtype: 'list',
                                title: '我',
                                cls: 'list2',
                                itemId: 'selfMenuList',
                                ui: 'round',
                                itemCls: 'list2_item',
                                itemTpl: [
                                    '<tpl if="needsIcon">',
                                    '    <img width="26" height="26" src="resources/images/self/{icon}.png" align="absmiddle"  />',
                                    '</tpl>{name}'
                                ],
                                store: 'SelfMenuStore'
                            }
                        ]
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom',
            itemId: 'mainTabBar'
        },
        listeners: [
            {
                fn: 'onSharedActivate',
                event: 'activate',
                delegate: '#shared'
            },
            {
                fn: 'onOfflineActivate',
                event: 'activate',
                delegate: '#offline'
            },
            {
                fn: 'onSelfActivate',
                event: 'activate',
                delegate: '#self'
            }
        ]
    },

    onSharedActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        //每次点击“已分享”都重新获取最新的列表
        Ext.getStore('SharedStore').loadPage(1, {"start":"0"}, this);
        newActiveItem.getComponent('sharedNavigateView').reset();

    },

    onOfflineActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var offlineStore = Ext.getStore('OfflineStore');
        var count = offlineStore.getAllCount();
        if(count === 0) {
            offlineStore.load();
        }
    },

    onSelfActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var selfMenuStore = Ext.getStore('SelfMenuStore');
        var count = selfMenuStore.getAllCount();
        if(count === 0) {
            selfMenuStore.load();
        }
    },

    initialize: function() {
        this.callParent();

        //加载任务列表
        Ext.getStore('TaskStore').loadPage(1, {"start":"0"}, this);
        //获取用户未完成任务数
        mobile.view.MyUtils.updateTaskCount();
    }

});