/*
 * File: app/view/RegisterForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.RegisterForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.registerform',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Label',
        'Ext.form.FieldSet',
        'Ext.field.Password',
        'Ext.field.Select',
        'Ext.field.Spinner'
    ],

    config: {
        height: '100%',
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '注册',
                items: [
                    {
                        xtype: 'button',
                        docked: 'left',
                        itemId: 'backBtn',
                        ui: 'back',
                        text: '返回'
                    }
                ]
            },
            {
                xtype: 'label',
                height: '100%',
                hidden: true,
                itemId: 'registerLabel',
                margin: 10,
                width: '90%'
            },
            {
                xtype: 'fieldset',
                itemId: 'registerFieldSet',
                margin: 20,
                items: [
                    {
                        xtype: 'textfield',
                        centered: false,
                        itemId: 'telephone',
                        labelWidth: '80%',
                        name: 'telephone',
                        maxLength: 11,
                        placeHolder: '请输入手机号码'
                    },
                    {
                        xtype: 'textfield',
                        centered: false,
                        hidden: true,
                        itemId: 'verifycode',
                        labelWidth: '80%',
                        name: 'verifycode',
                        maxLength: 6,
                        placeHolder: '请输入验证码'
                    },
                    {
                        xtype: 'textfield',
                        hidden: true,
                        itemId: 'wechatName',
                        label: '微信号',
                        name: 'wechatName',
                        maxLength: 30
                    },
                    {
                        xtype: 'passwordfield',
                        centered: false,
                        hidden: true,
                        itemId: 'password',
                        label: '密码',
                        name: 'password',
                        maxLength: 16,
                        placeHolder: '6到16个字符'
                    },
                    {
                        xtype: 'passwordfield',
                        centered: false,
                        hidden: true,
                        itemId: 'confirmPass',
                        label: '确认密码',
                        name: 'confirmPass',
                        maxLength: 16,
                        placeHolder: '6到16个字符'
                    },
                    {
                        xtype: 'selectfield',
                        hidden: true,
                        itemId: 'gender',
                        label: '性别',
                        name: 'gender',
                        options: [
                            {
                                text: '男',
                                value: '0'
                            },
                            {
                                text: '女',
                                value: '1'
                            }
                        ]
                    },
                    {
                        xtype: 'spinnerfield',
                        hidden: true,
                        itemId: 'age',
                        label: '年龄',
                        name: 'age',
                        maxValue: 100,
                        minValue: 1,
                        stepValue: 1,
                        defaultValue: 25
                    },
                    {
                        xtype: 'selectfield',
                        hidden: true,
                        itemId: 'provinceSelect',
                        label: '省份',
                        name: 'province',
                        displayField: 'name',
                        store: 'ProvinceStore',
                        valueField: 'id'
                    },
                    {
                        xtype: 'selectfield',
                        hidden: true,
                        itemId: 'citySelect',
                        label: '城市',
                        name: 'city',
                        displayField: 'name',
                        store: 'CityStore',
                        valueField: 'id',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    Ext.getStore('CityStore').filter('provinceId', '1');
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        hidden: true,
                        itemId: 'position',
                        label: '职业属性',
                        name: 'position',
                        options: [
                            {
                                text: '销售',
                                value: '1'
                            },
                            {
                                text: '技术',
                                value: '2'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'getVerifyCodeBtn',
                margin: 20,
                padding: 8,
                ui: 'action',
                text: '获取验证码'
            },
            {
                xtype: 'button',
                hidden: true,
                itemId: 'registerBtn',
                margin: 20,
                padding: 8,
                ui: 'action',
                text: '完成注册'
            },
            {
                xtype: 'button',
                hidden: true,
                itemId: 'submitVerifyCodeBtn',
                margin: 20,
                padding: 8,
                ui: 'action',
                text: '提交验证码'
            },
            {
                xtype: 'container',
                itemId: 'bottomContainer',
                margin: '10% 25% 0% 25%',
                width: '50%',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'label',
                        height: '100%',
                        hidden: true,
                        itemId: 'tipLabel',
                        padding: 0
                    },
                    {
                        xtype: 'button',
                        height: '100%',
                        hidden: true,
                        itemId: 'tipBtn',
                        padding: 0,
                        ui: 'plain'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onProvinceSelectChange11',
                event: 'change',
                delegate: '#provinceSelect'
            }
        ]
    },

    onProvinceSelectChange11: function(selectfield, newValue, oldValue, eOpts) {
        Ext.getStore('CityStore').filter('provinceId', newValue);
    }

});