/*
 * File: app/model/Shared.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.model.Shared', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'oid',
        fields: [
            {
                name: 'oid',
                type: 'string'
            },
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'imgUrl',
                type: 'string'
            },
            {
                name: 'contentUrl',
                type: 'string'
            },
            {
                name: 'price',
                type: 'float'
            },
            {
                name: 'sharedTime',
                type: 'string'
            },
            {
                name: 'status',
                type: 'string'
            },
            {
                name: 'articleId',
                type: 'string'
            },
            {
                name: 'photoUrl',
                type: 'string'
            },
            {
                name: 'reason',
                type: 'string'
            }
        ]
    }
});