/*
 * File: app/model/Task.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.model.Task', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'oid',
        fields: [
            {
                name: 'oid',
                type: 'string'
            },
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'amount',
                type: 'float'
            },
            {
                name: 'imgUrl',
                type: 'string'
            },
            {
                name: 'contentUrl',
                type: 'string'
            },
            {
                name: 'shareTimes',
                type: 'int'
            },
            {
                name: 'sharedCount',
                type: 'int'
            },
            {
                name: 'type',
                type: 'string'
            },
            {
                convert: function(v, rec) {
                    return rec.get('shareTimes') - rec.get('sharedCount');
                },
                name: 'shareAvaliable',
                type: 'int'
            }
        ]
    }
});