/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.model.User', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.LocalStorage'
    ],

    config: {
        fields: [
            {
                name: 'id',
                type: 'string'
            },
            {
                name: 'username',
                type: 'string'
            },
            {
                name: 'password',
                type: 'string'
            },
            {
                name: 'consumerId',
                type: 'string'
            },
            {
                name: 'gender',
                type: 'string'
            },
            {
                name: 'provinceId',
                type: 'string'
            },
            {
                name: 'cityId',
                type: 'string'
            },
            {
                name: 'positionId',
                type: 'string'
            },
            {
                name: 'age',
                type: 'int'
            },
            {
                name: 'wechatName',
                type: 'string'
            }
        ],
        proxy: {
            type: 'localstorage'
        }
    }
});