/*
 * File: app/view/self/MyInfo.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.self.MyInfo', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myinfo',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Spinner',
        'Ext.Button'
    ],

    config: {
        scrollable: true,
        items: [
            {
                xtype: 'fieldset',
                itemId: 'infoForm',
                items: [
                    {
                        xtype: 'textfield',
                        hidden: false,
                        itemId: 'wechatName',
                        label: '微信号',
                        name: 'wechatName',
                        maxLength: 30
                    },
                    {
                        xtype: 'selectfield',
                        label: '性别',
                        name: 'gender',
                        options: [
                            {
                                text: '男',
                                value: '0'
                            },
                            {
                                text: '女',
                                value: '1'
                            }
                        ]
                    },
                    {
                        xtype: 'spinnerfield',
                        label: '年龄',
                        name: 'age',
                        maxValue: 100,
                        minValue: 1,
                        stepValue: 1,
                        defaultValue: 25
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'provinceSelect',
                        label: '省份',
                        name: 'province',
                        displayField: 'name',
                        store: 'ProvinceStore',
                        valueField: 'id'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'citySelect',
                        label: '城市',
                        name: 'city',
                        displayField: 'name',
                        store: 'CityStore',
                        valueField: 'id',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    Ext.getStore('CityStore').filter('provinceId', '1');
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        label: '职业属性',
                        name: 'position',
                        options: [
                            {
                                text: '销售',
                                value: '1'
                            },
                            {
                                text: '技术',
                                value: '2'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'infoBtn',
                margin: 20,
                padding: 8,
                ui: 'confirm-round',
                text: '保存'
            }
        ],
        listeners: [
            {
                fn: 'onProvinceSelectChange1',
                event: 'change',
                delegate: '#provinceSelect'
            }
        ]
    },

    onProvinceSelectChange1: function(selectfield, newValue, oldValue, eOpts) {
        Ext.getStore('CityStore').filter('provinceId', newValue);
    },

    initialize: function() {
        this.callParent();

        var dataStore = Ext.getStore('UserStore');
        dataStore.load();
        var user = dataStore.getAt(0);
        this.setValues({
            wechatName: user.data.wechatName,
            gender: user.data.gender,
            age: user.data.age,
            province: 2,
            city: 3,
            position: 1

        });
    }

});