/*
 * File: app/view/self/MyPassword.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.self.MyPassword', {
    extend: 'Ext.form.Panel',
    alias: 'widget.mypassword',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Password',
        'Ext.Button'
    ],

    config: {
        height: '100%',
        scrollable: false,
        items: [
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'passwordfield',
                        itemId: 'oldPassword',
                        label: '旧密码',
                        name: 'oldPassword'
                    },
                    {
                        xtype: 'passwordfield',
                        itemId: 'newPassword',
                        label: '新密码',
                        name: 'newPassword',
                        placeHolder: '6到16个字符'
                    },
                    {
                        xtype: 'passwordfield',
                        itemId: 'confirmNewPass',
                        label: '确认密码',
                        name: 'confirmNewPass',
                        placeHolder: '6到16个字符'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'passBtn',
                margin: '3%',
                ui: 'confirm-round',
                text: '提交'
            }
        ]
    }

});