/*
 * File: app/view/self/Withdrawal.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.self.Withdrawal', {
    extend: 'Ext.Panel',
    alias: 'widget.withdrawal',

    requires: [
        'Ext.Container',
        'Ext.Label',
        'Ext.field.Number',
        'Ext.Button'
    ],

    config: {
        height: '100%',
        scrollable: false,
        items: [
            {
                xtype: 'container',
                itemId: 'labelContainer',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        html: '可提现余额：',
                        itemId: 'withdrawalLabel',
                        margin: '3% 0% 3% 3%',
                        width: 109
                    },
                    {
                        xtype: 'label',
                        height: 25,
                        itemId: 'balance',
                        margin: '3% 0%',
                        width: 70
                    }
                ]
            },
            {
                xtype: 'numberfield',
                itemId: 'claimAmount',
                margin: '2% 3%',
                label: '金额',
                labelWidth: '20%',
                name: 'claimAmount',
                placeHolder: '请输入提现金额'
            },
            {
                xtype: 'button',
                itemId: 'claimBtn',
                margin: '5% 3%',
                ui: 'confirm-round',
                text: '提现'
            }
        ]
    }

});