/*
 * File: app/view/self/WithdrawalHistory.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.self.WithdrawalHistory', {
    extend: 'Ext.Panel',
    alias: 'widget.withdrawalhistory',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'fit',
        scrollable: true,
        items: [
            {
                xtype: 'list',
                itemId: 'withdrawalHistoryList',
                disableSelection: true,
                itemTpl: [
                    '<div>',
                    '    时间：{createDate}',
                    '    <br/>',
                    '    提现金额：{amount}元',
                    '    <span style="margin-left:5px">',
                    '        状态：<tpl if="status==0">',
                    '            <font color="red">未到账</font>',
                    '        </tpl>',
                    '        <tpl if="status==10">',
                    '            <font color="blue">已到账</font>',
                    '        </tpl>',
                    '    </span>',
                    '</div>'
                ],
                loadingText: '正在加载...',
                store: 'WithdrawalHistoryStore'
            }
        ]
    }

});