/*
 * File: app/view/task/TaskDetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.task.TaskDetailPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.taskDetailPanel',

    requires: [
        'Ext.Button'
    ],

    config: {
        layout: 'fit',
        scrollable: true,
        items: [
            {
                xtype: 'button',
                docked: 'bottom',
                height: '5%',
                itemId: 'shareBtn',
                margin: '0 0 0 25%',
                ui: 'action-round',
                width: '50%',
                text: '我要抢单'
            }
        ]
    }

});