/*
 * File: app/controller/OfflineController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.controller.OfflineController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainPanel: 'mainpanel',
            offlineNavigateView: 'mainpanel #offlineNavigateView',
            offlineDetailPanel: '#offlineDetailPanel'
        },

        control: {
            "mainpanel #offline #offlineNavigateView #offlineList": {
                itemsingletap: 'onOfflineListItemTap'
            }
        }
    },

    onOfflineListItemTap: function(dataview, index, target, record, e, eOpts) {
        var offlineNavigateView = this.getOfflineNavigateView();
        offlineNavigateView.push({
            xtype: 'offlineDetailPanel',
            title: '下线明细'
        });

        var offlineDetailPanel = this.getOfflineDetailPanel();
        var offlineDetailList = offlineDetailPanel.getComponent('offlineDetailList');
        var consumerId = record.data.consumerId;

        var store = Ext.create('Ext.data.Store',{
            model: 'mobile.model.OfflineDetail',
            proxy: {
                type: 'jsonp',
                url: '/weixin/mobile/offline/getOfflineDetail.htm?consumerId='+consumerId,
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        });
        store.load();
        offlineDetailList.setStore(store);

    }

});