/*
 * File: app/controller/SharedController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.controller.SharedController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            sharedNavigateView: 'mainpanel #sharedNavigateView',
            sharedUploadPanel: 'sharedUploadPanel'
        },

        control: {
            "mainpanel #sharedNavigateView #sharedList": {
                itemsingletap: 'onSharedListItemTap'
            },
            "sharedUploadPanel #finishBtn": {
                tap: 'onFinishBtnTap'
            },
            "sharedUploadPanel #openUrl": {
                tap: 'onOpenUrlTap'
            }
        }
    },

    onSharedListItemTap: function(dataview, index, target, record, e, eOpts) {
        var sharedNavigateView = this.getSharedNavigateView();

        //未完成的分享到达上传照片页面
        sharedNavigateView.push({
            xtype: 'sharedUploadPanel',
            title: record.data.title,
            itemId: record.data
        });


    },

    onFinishBtnTap: function(button, e, eOpts) {
        //更新任务完成情况和已分享列表信息，并返回上级页面
        var historyId = button.getParent().getParent().getItemId().oid,
            user = mobile.view.MyUtils.getUserInfo();

        button.setDisabled(true);

        var successCallback = function(resp, ops) {
            var result = resp.responseText;
            if(result === 'success'){
                Ext.getStore('SharedStore').loadPage(1, {"start":"0"}, this);
                mobile.view.MyUtils.updateTaskCount();

                Ext.Msg.alert("提示", '提交成功');
            }
        };

        var failureCallback = function(resp, ops) {
            button.setDisabled(false);
            Ext.Msg.alert("提示", '网络连接超时');
        };

        Ext.Ajax.request({
            url: "/weixin/mobile/shared/finishShared.htm",
            params: {"historyId": historyId, "consumerId":user.consumerId},
            success: successCallback,
            failure: failureCallback
        });


    },

    onOpenUrlTap: function(button, e, eOpts) {
        var contentUrl = button.getParent().getParent().getItemId().contentUrl;
        window.open(contentUrl, '_system');
    }

});