/*
 * File: app/controller/TaskController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.controller.TaskController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainPanel: 'mainpanel',
            taskNavigateView: 'mainpanel #taskNavigateView',
            taskDetailPanel: 'taskDetailPanel'
        },

        control: {
            "mainpanel #article #taskNavigateView #taskList": {
                itemsingletap: 'onTaskListSelect'
            },
            "taskDetailPanel #shareBtn": {
                tap: 'onSharedButtonTap'
            }
        }
    },

    onTaskListSelect: function(dataview, index, target, record, e, eOpts) {

        var taskNavigateView = this.getTaskNavigateView();

        // 连接请求接口成功
        var successCallback = function(resp, ops) {
            var respHtml = resp.responseText;

            // Navigate to details
            taskNavigateView.push({
                xtype: 'taskDetailPanel',
                title: record.data.title,
                itemId: record.data.oid,
                html: respHtml
            });
        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            Ext.Msg.alert("提示", '网络连接超时');
        };


        // 请求网页内容
        Ext.Ajax.request({
            url: "/weixin/mobile/getHtmlContent.htm",
            params: {"url": record.data.contentUrl},
            success: successCallback,
            failure: failureCallback
        });

    },

    onSharedButtonTap: function(button, e, eOpts) {
        button.setDisabled(true);

        var articleId = button.getParent().getItemId(),
            mainPanel = this.getMainPanel(),
            user = mobile.view.MyUtils.getUserInfo();

        var successCallback = function(resp, ops) {
            var result = resp.responseText;
            if(result === '0'){
                Ext.Msg.alert("提示", '您已完成过此任务');

            } else if(result === '1'){
                Ext.Msg.alert("提示", '恭喜您，抢单成功！');
                mobile.view.MyUtils.updateTaskCount();

            } else if(result === '2'){
                Ext.Msg.alert("提示", '此任务次数已被抢完');
            }
        };

        var failureCallback = function(resp, ops) {
            button.setDisabled(false);
            Ext.Msg.alert("提示", '网络连接超时');
        };

        Ext.Ajax.request({
            url: "/weixin/mobile/article/shareArticle.htm",
            params: {"articleId": articleId, "consumerId":user.consumerId},
            success: successCallback,
            failure: failureCallback
        });

    }

});