/*
 * File: app/controller/UserController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.controller.UserController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            loginPanel: 'loginform',
            registerPanel: 'registerform',
            forgetPanel: 'forgetform',
            mainPanel: 'mainpanel',
            verifycodeField: 'registerform #registerFieldSet #verifycode',
            passwordField: 'registerform #registerFieldSet #password',
            passLabel: 'registerform #passLabel',
            registerLabel: 'registerform #registerLabel',
            submitVerifyCodeBtn: 'registerform #submitVerifyCodeBtn',
            registerBtn: 'registerform #registerBtn'
        },

        control: {
            "registerform #backBtn": {
                tap: 'backToLogin'
            },
            "forgetform #backBtn": {
                tap: 'forgetBackBtnTap'
            },
            "loginform #registerBtn": {
                tap: 'showRegister'
            },
            "loginform #loginButton": {
                tap: 'login'
            },
            "registerform #getVerifyCodeBtn": {
                tap: 'getVerifyCode'
            },
            "forgetform #getVerifyCodeBtn": {
                tap: 'forgetGetVerifyCode'
            },
            "registerform #submitVerifyCodeBtn": {
                tap: 'validateVerifyCode'
            },
            "forgetform #submitVerifyCodeBtn": {
                tap: 'forgetValidateVerifyCode'
            },
            "registerform #bottomContainer #tipBtn": {
                tap: 'getOneMoreCode'
            },
            "forgetform #bottomContainer #tipBtn": {
                tap: 'forgetGetOneMoreCOde'
            },
            "registerform #registerBtn": {
                tap: 'register'
            },
            "forgetform #submitBtn": {
                tap: 'forgetSubmit'
            },
            "loginform #forgetBtn": {
                tap: 'onForgetBtnTap'
            }
        }
    },

    backToLogin: function(button, e, eOpts) {
        var registerForm = this.getRegisterPanel();
        var loginForm = Ext.createByAlias('widget.loginform');
        Ext.Viewport.add(loginForm);
        loginForm.show();
        registerForm.destroy();

    },

    forgetBackBtnTap: function(button, e, eOpts) {
        var forgetForm = this.getForgetPanel();
        var loginForm = Ext.createByAlias('widget.loginform');
        Ext.Viewport.add(loginForm);
        loginForm.show();
        forgetForm.destroy();

    },

    showRegister: function(button, e, eOpts) {
        var registerForm = Ext.createByAlias('widget.registerform');
        var loginForm = this.getLoginPanel();
        Ext.Viewport.add(registerForm);
        loginForm.destroy();
        registerForm.show();

    },

    login: function(button, e, eOpts) {
        var form = button.up('formpanel'),			// Login form
            values = form.getValues(),				// Form values
            loginPanel = this.getLoginPanel(),
            mainPanel = this.getMainPanel();

        if(values.j_username === '' || values.j_password === ''){
            Ext.Msg.alert("提示", '用户名和密码不能为空');
            return;
        }

        button.setDisabled(true);

        // 连接登录接口成功
        var successCallback = function(resp, ops) {
            var loginResult = resp.responseText;
            if(loginResult === 'failure'){
                button.setDisabled(false);
                Ext.Msg.alert("登录失败", '用户名或密码不正确');
            } else {
                //保存用户信息,下次打开直接到达主页
                var user = Ext.JSON.decode(loginResult);
                var store = Ext.create('mobile.model.User', {
                    username : values.j_username,
                    password : values.j_password,
                    id : user.id,
                    consumerId : user.consumerId,
                    wechatName : user.wechatName,
                    age : user.age,
                    gender : user.gender,
                    provinceId : user.provinceId,
                    cityId : user.cityId,
                    positionId : user.positionId
                });
                store.save();

                if(typeof(mainPanel) === 'undefined'){
                    mainPanel = Ext.createByAlias('widget.mainpanel');
                } else {
                    //加载任务列表
                    Ext.getStore('TaskStore').loadPage(1, {"start":"0"}, this);
                }
                loginPanel.destroy();
                Ext.Viewport.add(mainPanel);
                mainPanel.show();
                mainPanel.setActiveItem(0);
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            button.setDisabled(false);
            Ext.Msg.alert("提示", '网络连接超时');

        };


        // 登录请求
        Ext.Ajax.request({
            url: "/weixin/mobile/j_spring_security_check",
            params: values,
            success: successCallback,
            failure: failureCallback
        });

    },

    getVerifyCode: function(button, e, eOpts) {

        var form = button.up('formpanel'),			// Register form
            values = form.getValues(),				// Form values
            registerForm = this.getRegisterPanel(),
            me = this;

        var reg = /^1(?:[38]\d|4[57]|5[01256789])\d{8}$/;
        if(!reg.test(values.telephone)){
            Ext.Msg.alert("提示", '请输入正确的手机号码');
            return;
        }

        button.setDisabled(true);

        // 请求成功
        var successCallback = function(resp, ops) {
            var registerResult = resp.responseText;
            if(registerResult === 'success') {
                var telephone = registerForm.getComponent('registerFieldSet').getComponent('telephone');
                var getVerifyCodeBtn = registerForm.getComponent('getVerifyCodeBtn');
                telephone.setHidden(true);
                getVerifyCodeBtn.setHidden(true);

                var verifycode = registerForm.getComponent('registerFieldSet').getComponent('verifycode');
                var submitVerifyCodeBtn = registerForm.getComponent('submitVerifyCodeBtn');
                var registerLabel = registerForm.getComponent('registerLabel');
                verifycode.setHidden(false);
                submitVerifyCodeBtn.setHidden(false);
                registerLabel.setHidden(false);
                registerLabel.setHtml('您的手机号码:'+values.telephone+'<br>将会收到一条包含验证码的短信.');


                var tipLabel = registerForm.getComponent('bottomContainer').getComponent('tipLabel');
                tipLabel.setHidden(false);
                me.countDownMinute(tipLabel, "register");

            } else if(registerResult === 'existed') {
                button.setDisabled(false);
                Ext.Msg.alert("提示", '该手机号已注册');
            } else {
                button.setDisabled(false);
                Ext.Msg.alert("提示", '获取验证码失败，请重试');
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            button.setDisabled(false);
            Ext.Msg.alert("提示", '网络连接超时');
        };

        // 请求验证码
        Ext.Ajax.request({
            url: "/weixin/mobile/register/getVerifyCode.htm",
            params: values,
            success: successCallback,
            failure: failureCallback
        });

    },

    forgetGetVerifyCode: function(button, e, eOpts) {
        var form = button.up('formpanel'),
            values = form.getValues(),
            forgetForm = this.getForgetPanel(),
            me = this;

        var reg = /^1(?:[38]\d|4[57]|5[01256789])\d{8}$/;
        if(!reg.test(values.telephone)) {
            Ext.Msg.alert("提示", '请输入正确的手机号码');
            return;
        } else if(values.wechatName === '') {
            Ext.Msg.alert("提示", '请输入微信号');
            return;
        }

        button.setDisabled(true);

        // 请求成功
        var successCallback = function(resp, ops) {
            var result = resp.responseText;
            if(result === 'success') {
                var firstLabel = forgetForm.getComponent('firstLabel');
                var telephone = forgetForm.getComponent('forgetFieldSet').getComponent('telephone');
                var wechatName = forgetForm.getComponent('forgetFieldSet').getComponent('wechatName');
                var getVerifyCodeBtn = forgetForm.getComponent('getVerifyCodeBtn');
                firstLabel.setHidden(true);
                telephone.setHidden(true);
                wechatName.setHidden(true);
                getVerifyCodeBtn.setHidden(true);

                var verifycode = forgetForm.getComponent('forgetFieldSet').getComponent('verifycode');
                var submitVerifyCodeBtn = forgetForm.getComponent('submitVerifyCodeBtn');
                var forgetLabel = forgetForm.getComponent('forgetLabel');
                verifycode.setHidden(false);
                submitVerifyCodeBtn.setHidden(false);
                forgetLabel.setHidden(false);
                forgetLabel.setHtml('您正在找回账号:'+values.telephone+'的密码.请输入手机收到的验证码：');

                var tipLabel = forgetForm.getComponent('bottomContainer').getComponent('tipLabel');
                tipLabel.setHidden(false);
                me.countDownMinute(tipLabel, "forget");

            } else if(result === 'notExist') {
                button.setDisabled(false);
                Ext.Msg.alert("提示", '手机号与微信号不匹配');

            } else {
                button.setDisabled(false);
                Ext.Msg.alert("提示", '获取验证码失败，请重试');
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            button.setDisabled(false);
            Ext.Msg.alert("提示", '网络连接超时');
        };

        // 请求验证码
        Ext.Ajax.request({
            url: "/weixin/mobile/forget/getVerifyCode.htm",
            params: values,
            success: successCallback,
            failure: failureCallback
        });

    },

    validateVerifyCode: function(button, e, eOpts) {

        var form = button.up('formpanel'),
            values = form.getValues(),
            registerForm = this.getRegisterPanel();

        if(values.verifycode === '' || values.verifycode.length !== 6){
            Ext.Msg.alert("提示", '请输入正确的验证码');
            return;
        }

        button.setDisabled(true);

        // 验证请求成功
        var successCallback = function(resp, ops) {
            var registerResult = resp.responseText;
            if(registerResult === 'success') {
                var verifycode = registerForm.getComponent('registerFieldSet').getComponent('verifycode');
                var submitVerifyCodeBtn = registerForm.getComponent('submitVerifyCodeBtn');
                var registerLabel = registerForm.getComponent('registerLabel');
                var bottomContainer = registerForm.getComponent('bottomContainer');
                verifycode.setHidden(true);
                submitVerifyCodeBtn.setHidden(true);
                registerLabel.setHidden(true);
                bottomContainer.setHidden(true);

                var wechatName = registerForm.getComponent('registerFieldSet').getComponent('wechatName');
                var password = registerForm.getComponent('registerFieldSet').getComponent('password');
                var confirmPass = registerForm.getComponent('registerFieldSet').getComponent('confirmPass');
                var gender = registerForm.getComponent('registerFieldSet').getComponent('gender');
                var age = registerForm.getComponent('registerFieldSet').getComponent('age');
                var provinceSelect = registerForm.getComponent('registerFieldSet').getComponent('provinceSelect');
                var citySelect = registerForm.getComponent('registerFieldSet').getComponent('citySelect');
                var position = registerForm.getComponent('registerFieldSet').getComponent('position');
                var registerBtn = registerForm.getComponent('registerBtn');
                wechatName.setHidden(false);
                password.setHidden(false);
                confirmPass.setHidden(false);
                gender.setHidden(false);
                age.setHidden(false);
                provinceSelect.setHidden(false);
                citySelect.setHidden(false);
                position.setHidden(false);
                registerBtn.setHidden(false);

            } else {
                button.setDisabled(false);
                Ext.Msg.alert("提示", '请输入正确的验证码');
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            button.setDisabled(false);
            Ext.Msg.alert("提示", '网络连接超时');
        };

        // 验证手机验证码
        Ext.Ajax.request({
            url: "/weixin/mobile/register/validateVerifyCode.htm",
            params: values,
            success: successCallback,
            failure: failureCallback
        });

    },

    forgetValidateVerifyCode: function(button, e, eOpts) {

        var form = button.up('formpanel'),
            values = form.getValues(),
            forgetForm = this.getForgetPanel();

        if(values.verifycode === '' || values.verifycode.length !== 6){
            Ext.Msg.alert("提示", '请输入正确的验证码');
            return;
        }

        button.setDisabled(true);

        // 验证请求成功
        var successCallback = function(resp, ops) {
            var result = resp.responseText;
            if(result === 'success') {
                var verifycode = forgetForm.getComponent('forgetFieldSet').getComponent('verifycode');
                var submitVerifyCodeBtn = forgetForm.getComponent('submitVerifyCodeBtn');
                var forgetLabel = forgetForm.getComponent('forgetLabel');
                var bottomContainer = forgetForm.getComponent('bottomContainer');
                verifycode.setHidden(true);
                submitVerifyCodeBtn.setHidden(true);
                forgetLabel.setHidden(true);
                bottomContainer.setHidden(true);

                var passLabel = forgetForm.getComponent('passLabel');
                var password = forgetForm.getComponent('forgetFieldSet').getComponent('password');
                var submitBtn = forgetForm.getComponent('submitBtn');
                passLabel.setHidden(false);
                password.setHidden(false);
                submitBtn.setHidden(false);

            } else {
                button.setDisabled(false);
                Ext.Msg.alert("提示", '请输入正确的验证码');
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            button.setDisabled(false);
            Ext.Msg.alert("提示", '网络连接超时');
        };

        // 验证手机验证码
        Ext.Ajax.request({
            url: "/weixin/mobile/register/validateVerifyCode.htm",
            params: values,
            success: successCallback,
            failure: failureCallback
        });

    },

    getOneMoreCode: function(button, e, eOpts) {
        var registerForm = this.getRegisterPanel();
        var telephone = registerForm.getComponent('registerFieldSet').getComponent('telephone');
        var phone = telephone.getValue();
        var me = this;

        // 请求成功
        var successCallback = function(resp, ops) {
            var registerResult = resp.responseText;
            if(registerResult === 'success') {
                var tipBtn = registerForm.getComponent('bottomContainer').getComponent('tipBtn');
                tipBtn.setHidden(true);
                tipBtn.setText('');

                var tipLabel = registerForm.getComponent('bottomContainer').getComponent('tipLabel');
                tipLabel.setHtml('');
                me.countDownMinute(tipLabel);

            } else {
                 Ext.Msg.alert("提示", '获取验证码失败，请重试');
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            Ext.Msg.alert("提示", '网络连接超时');
        };

        // 请求验证码
        Ext.Ajax.request({
            url: "/weixin/mobile/register/getVerifyCode.htm",
            params: {"telephone": phone},
            success: successCallback,
            failure: failureCallback
        });
    },

    forgetGetOneMoreCOde: function(button, e, eOpts) {
        var forgetForm = this.getForgetPanel();
        var telephone = forgetForm.getComponent('forgetFieldSet').getComponent('telephone');
        var wechat = forgetForm.getComponent('forgetFieldSet').getComponent('wechatName');
        var phone = telephone.getValue();
        var wechatName = wechat.getValue();
        var me = this;

        // 请求成功
        var successCallback = function(resp, ops) {
            var registerResult = resp.responseText;
            if(registerResult === 'success') {
                var tipBtn = forgetForm.getComponent('bottomContainer').getComponent('tipBtn');
                tipBtn.setHidden(true);
                tipBtn.setText('');

                var tipLabel = forgetForm.getComponent('bottomContainer').getComponent('tipLabel');
                tipLabel.setHtml('');
                me.countDownMinute(tipLabel);

            } else {
                 Ext.Msg.alert("提示", '获取验证码失败，请重试');
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            Ext.Msg.alert("提示", '网络连接超时');
        };

        // 请求验证码
        Ext.Ajax.request({
            url: "/weixin/mobile/forget/getVerifyCode.htm",
            params: {"telephone": phone, "wechatName":wechatName},
            success: successCallback,
            failure: failureCallback
        });
    },

    register: function(button, e, eOpts) {
        var form = button.up('formpanel'),			// Register form
            values = form.getValues(),				// Form values
            registerForm = this.getRegisterPanel();

        if(values.wechatName === '') {
            Ext.Msg.alert("提示", '微信号不能为空');
            return;
        } else if(values.password === '') {
            Ext.Msg.alert("提示", '密码不能为空');
            return;
        } else if(values.password.length>16 || values.password.length<6) {
            Ext.Msg.alert("提示", '密码长度为6到16个字符，请确认');
            return;
        } else if(values.confirmPass === '') {
            Ext.Msg.alert("提示", '确认密码不能为空');
            return;
        } else if(values.password !== values.confirmPass) {
            Ext.Msg.alert("提示", '密码不一致');
            return;
        }

        button.setDisabled(true);

        // 请求成功
        var successCallback = function(resp, ops) {
            var registerResult = resp.responseText;
            if(registerResult === 'success') {
                Ext.Msg.alert("提示", '恭喜您，注册成功');
                registerForm.destroy();

                var loginPanel = Ext.createByAlias('widget.loginform');
                var username = loginPanel.getComponent('loginFieldSet').getComponent('username');
                username.setValue(values.telephone);
                Ext.Viewport.add(loginPanel);
                loginPanel.show();

            } else {
                button.setDisabled(false);
                Ext.Msg.alert("提示", '注册失败，请重试');
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            button.setDisabled(false);
            Ext.Msg.alert("提示", '网络连接超时');
        };

        // 请求完成注册
        Ext.Ajax.request({
            url: "/weixin/mobile/register/finishRegister.htm",
            params: values,
            success: successCallback,
            failure: failureCallback
        });
    },

    forgetSubmit: function(button, e, eOpts) {
        var form = button.up('formpanel'),			// Register form
            values = form.getValues(),				// Form values
            forgetForm = this.getForgetPanel();

        if(values.password === '') {
            Ext.Msg.alert("提示", '密码不能为空');
            return;
        } else if(values.password.length>16 || values.password.length<6) {
            Ext.Msg.alert("提示", '密码长度为6到16个字符，请确认');
            return;
        }

        button.setDisabled(true);

        // 请求成功
        var successCallback = function(resp, ops) {
            var registerResult = resp.responseText;
            if(registerResult === 'success') {
                Ext.Msg.alert("提示", '密码设置成功');
                forgetForm.destroy();

                var loginPanel = Ext.createByAlias('widget.loginform');
                var username = loginPanel.getComponent('loginFieldSet').getComponent('username');
                username.setValue(values.telephone);
                Ext.Viewport.add(loginPanel);
                loginPanel.show();

            } else {
                button.setDisabled(false);
                Ext.Msg.alert("提示", '系统繁忙，请重试');
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {
            button.setDisabled(false);
            Ext.Msg.alert("提示", '网络连接超时');
        };

        // 请求完成注册
        Ext.Ajax.request({
            url: "/weixin/mobile/forget/forgetSubmit.htm",
            params: values,
            success: successCallback,
            failure: failureCallback
        });
    },

    onForgetBtnTap: function(button, e, eOpts) {
        var forgetForm = Ext.createByAlias('widget.forgetform');
        var loginForm = this.getLoginPanel();
        Ext.Viewport.add(forgetForm);
        loginForm.destroy();
        forgetForm.show();
    },

    countDownMinute: function(target, type) {
        var me = this;
        var now = new Date();
        var to = Ext.Date.add(now, Ext.Date.SECOND, 60);
        me.task = setInterval(function(){ me.timing(me, target, to, type); }, 1000);
    },

    timing: function(me, target, to, type) {
        var targetForm;
        if(type === 'register'){
           targetForm = this.getRegisterPanel();
        } else {
           targetForm = this.getForgetPanel();
        }

        var now = new Date();
        var ms = to - now;
        var second = Math.floor(ms / 1000) % 60;
        if (second >= 0) {
            target.setHtml(Ext.String.format('<font color="blue">{0}</font>秒后重新发送', second));
        } else {
            target.setHtml('没收到？');
            var tipBtn = targetForm.getComponent('bottomContainer').getComponent('tipBtn');
            tipBtn.setHidden(false);
            tipBtn.setText('<font color="blue">重新发送</font');

            clearInterval(me.task);
        }
    }

});