/*
 * File: app/view/offline/OfflineDetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.offline.OfflineDetailPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.offlineDetailPanel',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        id: 'offlineDetailPanel',
        layout: 'fit',
        scrollable: true,
        items: [
            {
                xtype: 'list',
                itemId: 'offlineDetailList',
                itemTpl: [
                    '<div>',
                    '    <span style="font-size:14px">文章标题：<br>分享时间：{sharedDate}</span>',
                    '    <span style="margin-left:10%;color:blue">{sharedPay}元</span>',
                    '</div>'
                ],
                loadingText: '正在加载...'
            }
        ]
    }

});