/*
 * File: app/view/shared/SharedUploadPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mobile.view.shared.SharedUploadPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.sharedUploadPanel',

    requires: [
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.field.File',
        'Ext.Button'
    ],

    config: {
        layout: 'fit',
        scrollable: true,
        items: [
            {
                xtype: 'formpanel',
                itemId: 'uploadPanel',
                items: [
                    {
                        xtype: 'image',
                        height: 200,
                        itemId: 'preview',
                        margin: '3% 20%',
                        width: 200,
                        src: 'resources/images/200x200.gif'
                    },
                    {
                        xtype: 'filefield',
                        itemId: 'file',
                        margin: '3% 5%',
                        labelWidth: '0%',
                        name: 'file',
                        multiple: true
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            var form = button.up('formpanel');
                            var image = form.getComponent('preview');
                            var finishBtn = form.getComponent('finishBtn');
                            var progressIndicator = Ext.create("Ext.ProgressIndicator",{loadingText:{
                                upload: '正在上传: {percent}%',
                                download: '{percent}%'
                            }});
                            var historyId = button.getParent().getParent().getItemId().oid;

                            var request = {
                                url: '/weixin/mobile/shared/upload.htm?historyId='+historyId,
                                method: 'POST',
                                xhr2: true,
                                progress: progressIndicator,
                                success: function(form, response) {
                                    if(response) {
                                        image.setSrc(response.filePath);
                                        finishBtn.setDisabled(false);
                                        button.setDisabled(false);

                                        Ext.getStore('SharedStore').loadPage(1, {"start":"0"}, this);
                                    }
                                },
                                failure: function(form, response) {
                                    console.log("upload failure");
                                    finishBtn.setDisabled(true);
                                    button.setDisabled(false);
                                }
                            };
                            var input = Ext.Viewport.down("filefield").getComponent().input;
                            var files = input.dom.files;
                            if (files.length) {
                                if(files[0].size > 2097152) {
                                    Ext.Msg.alert("图片大小不能超过2MB");
                                    return;
                                }
                            } else {
                                Ext.Msg.alert("请选择一张图片");
                                return;
                            }

                            button.setDisabled(true);
                            form.submit(request);
                        },
                        itemId: 'uploadBtn',
                        margin: '3% 5%',
                        ui: 'confirm',
                        text: '上传图片'
                    },
                    {
                        xtype: 'button',
                        disabled: true,
                        itemId: 'finishBtn',
                        margin: '3% 5%',
                        ui: 'decline',
                        text: '提交审核'
                    },
                    {
                        xtype: 'button',
                        disabled: false,
                        itemId: 'openUrl',
                        margin: '3% 5%',
                        ui: 'action',
                        text: '打开链接'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();

        var photoUrl = this.getItemId().photoUrl;
        var status = this.getItemId().status;

        if(photoUrl){
            var preview = this.getComponent('uploadPanel').getComponent('preview');
            preview.setSrc(photoUrl);
        }
        if(status === '1'){
            this.getComponent('uploadPanel').getComponent("finishBtn").setDisabled(false);
        } else if(status === '3'){
            this.getComponent('uploadPanel').getComponent("uploadBtn").setDisabled(true);
        }
    }

});